// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {domain} from '../models';

export function CreateAccount(arg1:domain.AccountDTO):Promise<void>;

export function CreateAccountSample(arg1:domain.AccountDTO):Promise<number>;

export function CreateTransaction(arg1:domain.TransactionDTO):Promise<void>;

export function CreateTransactionSample(arg1:domain.TransactionDTO):Promise<number>;

export function DeleteAccount(arg1:number):Promise<void>;

export function DeleteTag(arg1:number):Promise<void>;

export function DeleteTransaction(arg1:number):Promise<void>;

export function GetAccountByID(arg1:number):Promise<domain.AccountDTO>;

export function GetAccountIDByName(arg1:string):Promise<number>;

export function GetAccountList():Promise<Array<domain.AccountDTO>>;

export function GetTagList():Promise<Array<domain.Tag>>;

export function GetTransactionByID(arg1:number):Promise<domain.TransactionDTO>;

export function GetTransactionList():Promise<Array<domain.TransactionDTO>>;

export function Greet(arg1:string):Promise<string>;

export function SearchAccount(arg1:string):Promise<Array<domain.AccountDTO>>;

export function SubmitAccount(arg1:any,arg2:domain.AccountDTO):Promise<void>;

export function UpdateAccount(arg1:domain.AccountDTO):Promise<void>;

export function UpdateTag(arg1:number,arg2:string):Promise<void>;

export function UpdateTransaction(arg1:domain.TransactionDTO):Promise<void>;
