// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateAccount(arg1) {
  return window['go']['main']['App']['CreateAccount'](arg1);
}

export function CreateAccountSample(arg1) {
  return window['go']['main']['App']['CreateAccountSample'](arg1);
}

export function CreateTransaction(arg1) {
  return window['go']['main']['App']['CreateTransaction'](arg1);
}

export function CreateTransactionSample(arg1) {
  return window['go']['main']['App']['CreateTransactionSample'](arg1);
}

export function GetAccountID(arg1) {
  return window['go']['main']['App']['GetAccountID'](arg1);
}

export function GetTransactionByID(arg1) {
  return window['go']['main']['App']['GetTransactionByID'](arg1);
}

export function GetTransactionList() {
  return window['go']['main']['App']['GetTransactionList']();
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function SubmitTransaction(arg1, arg2) {
  return window['go']['main']['App']['SubmitTransaction'](arg1, arg2);
}

export function UpdateTransaction(arg1) {
  return window['go']['main']['App']['UpdateTransaction'](arg1);
}
