// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateAccount(arg1) {
  return window['go']['main']['App']['CreateAccount'](arg1);
}

export function CreateAccountSample(arg1) {
  return window['go']['main']['App']['CreateAccountSample'](arg1);
}

export function CreateTransaction(arg1) {
  return window['go']['main']['App']['CreateTransaction'](arg1);
}

export function CreateTransactionSample(arg1) {
  return window['go']['main']['App']['CreateTransactionSample'](arg1);
}

export function DeleteAccount(arg1) {
  return window['go']['main']['App']['DeleteAccount'](arg1);
}

export function DeleteTag(arg1) {
  return window['go']['main']['App']['DeleteTag'](arg1);
}

export function DeleteTransaction(arg1) {
  return window['go']['main']['App']['DeleteTransaction'](arg1);
}

export function GetAccountByID(arg1) {
  return window['go']['main']['App']['GetAccountByID'](arg1);
}

export function GetAccountIDByName(arg1) {
  return window['go']['main']['App']['GetAccountIDByName'](arg1);
}

export function GetAccountList() {
  return window['go']['main']['App']['GetAccountList']();
}

export function GetTagList() {
  return window['go']['main']['App']['GetTagList']();
}

export function GetTransactionByID(arg1) {
  return window['go']['main']['App']['GetTransactionByID'](arg1);
}

export function GetTransactionList() {
  return window['go']['main']['App']['GetTransactionList']();
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function SearchAccount(arg1) {
  return window['go']['main']['App']['SearchAccount'](arg1);
}

export function SubmitAccount(arg1, arg2) {
  return window['go']['main']['App']['SubmitAccount'](arg1, arg2);
}

export function UpdateAccount(arg1) {
  return window['go']['main']['App']['UpdateAccount'](arg1);
}

export function UpdateTag(arg1, arg2) {
  return window['go']['main']['App']['UpdateTag'](arg1, arg2);
}

export function UpdateTransaction(arg1) {
  return window['go']['main']['App']['UpdateTransaction'](arg1);
}
