// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {domain} from '../models';

export function CreateAccount(arg1:domain.AccountDTO):Promise<domain.AccountDTO>;

export function CreateAccountSample(arg1:domain.AccountDTO):Promise<number>;

export function CreateTransaction(arg1:domain.TransactionDTO):Promise<domain.TransactionDTO>;

export function CreateTransactionSample(arg1:domain.TransactionDTO):Promise<number>;

export function GetAccountID(arg1:string):Promise<number>;

export function GetTransactionByID(arg1:number):Promise<domain.TransactionDTO>;

export function GetTransactionList():Promise<Array<domain.TransactionDTO>>;

export function Greet(arg1:string):Promise<string>;

export function SubmitTransaction(arg1:any,arg2:domain.TransactionDTO):Promise<domain.TransactionDTO>;

export function UpdateTransaction(arg1:domain.TransactionDTO):Promise<domain.TransactionDTO>;
